version: "3.9"

services:
  docker:
    image: docker:24.0-dind
    privileged: true
    volumes:
      - ./docker/daemon.json:/etc/docker/daemon.json:ro
  runner:
    build: .
    environment:
      - DOCKER_HOST=docker
      - REPO_URL
      - REGISTRATION_TOKEN
      - RUNNER_NAME
      - RUNNER_LABLES
      - RUNNER_ALLOW_RUNASROOT=1
