version: "3.9"

services:
  docker:
    image: docker:24.0-dind
    privileged: true
  runner:
    image: zhangyuan/github-actions-runner:add-image
    command: run
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - REPO_URL
      - REGISTRATION_TOKEN
      - RUNNER_NAME
      - RUNNER_LABLES
      - RUNNER_ALLOW_RUNASROOT=1
