version: "3.9"

services:
  dind:
    image: docker:24.0-dind
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375"]
    privileged: true
  runner:
    image: zhangyuan/github-actions-runner:v0.0.1
    command: run
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - REPO_URL
      - REGISTRATION_TOKEN
      - RUNNER_NAME
      - RUNNER_LABLES
      - RUNNER_ALLOW_RUNASROOT=1
